import Link from 'next/link'

export const metadata = {
  title: 'Privacy Policy — HomeLink Ethiopia',
  description: 'How HomeLink Ethiopia collects, uses, and protects your personal data.',
}

export default function PrivacyPage() {
  return (
    <div className="bg-cream py-16">
      <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8">
        <p className="font-mono text-xs uppercase tracking-widest text-rust">Legal</p>
        <h1 className="mt-2 font-display text-3xl font-semibold text-charcoal sm:text-4xl">Privacy Policy</h1>
        <p className="mt-1 text-sm text-charcoal/60">Last updated: September 2026</p>

        <div className="mt-10 space-y-8 text-sm leading-relaxed text-charcoal/75">
          <section>
            <h2 className="font-display text-lg font-bold text-charcoal">1. What we collect</h2>
            <p className="mt-2">
              Account details (name, email, phone), role-specific information (landlord identity documents,
              tenant preferences), property data, messages sent through the platform, and technical logs such as
              IP addresses for security auditing.
            </p>
          </section>
          <section>
            <h2 className="font-display text-lg font-bold text-charcoal">2. How we use it</h2>
            <p className="mt-2">
              To verify landlords and properties, compute tenant credit scores, match tenants to homes, process
              rent ledgers, resolve disputes and maintenance tickets, and keep the platform safe. We do not sell
              your personal data.
            </p>
          </section>
          <section>
            <h2 className="font-display text-lg font-bold text-charcoal">3. AI processing</h2>
            <p className="mt-2">
              Fair-rent estimates, fraud-risk scores, and neighborhood ratings are generated by models trained on
              platform data. These outputs are decision-support only — a human always makes the final call — and
              are described in our{' '}
              <Link href="/ai-transparency" className="font-semibold text-rust hover:text-rust-dark">AI transparency page</Link>.
            </p>
          </section>
          <section>
            <h2 className="font-display text-lg font-bold text-charcoal">4. Sharing</h2>
            <p className="mt-2">
              Your name and contact details are shared with the counterparty of an agreement you enter (e.g. your
              landlord or tenant). Documents you upload are visible only to our verification team. We disclose
              data to authorities only where Ethiopian law requires it.
            </p>
          </section>
          <section>
            <h2 className="font-display text-lg font-bold text-charcoal">5. Your rights</h2>
            <p className="mt-2">
              You can access, correct, or delete your profile data at any time from Settings, or by contacting
              support. Deleting your account removes personal data within 30 days, except records we must keep
              for legal or dispute-resolution purposes (e.g. rent ledgers).
            </p>
          </section>
          <section>
            <h2 className="font-display text-lg font-bold text-charcoal">6. Cookies</h2>
            <p className="mt-2">
              We use a small set of essential cookies for sign-in sessions and language preference — see our{' '}
              <Link href="/legal/cookies" className="font-semibold text-rust hover:text-rust-dark">Cookie Policy</Link>.
            </p>
          </section>
        </div>
      </div>
    </div>
  )
}
