// ============================================================
// 13. FRAUD REPORTS (FR-11)
// Centralized Trust & Safety collection.
// Combines user-submitted complaints with automated AI risk signals
// to help admins quickly triage and resolve scams.
// ============================================================
const FraudReportSchema = {
  // Unique database identifier
  _id: ObjectId,
  
  // ─────────────────────────────────────────────────────────────
  // CORE RELATIONSHIPS
  // ─────────────────────────────────────────────────────────────
  
  // The user who filed the report
  reportedBy: { type: ObjectId, ref: "Account", required: true },
  
  // Optional: The specific listing being reported
  reportedPropertyId: { type: ObjectId, ref: "Property" },
  
  // Optional: The specific user acting suspiciously
  reportedUserId: { type: ObjectId, ref: "Account" },
  
  // Audit trail: The admin currently investigating the case
  reviewedBy: { type: ObjectId, ref: "Account" }, 

  // ─────────────────────────────────────────────────────────────
  // REPORT DETAILS (Human Input)
  // ─────────────────────────────────────────────────────────────
  category: {
    type: String,
    enum: [
      "fake_listing",       // Listing doesn't actually exist
      "duplicate_listing",  // Copied from a real landlord
      "image_theft",        // Stolen photos
      "scam",               // Asking for money outside the platform
      "impersonation",      // Pretending to be someone else
      "other"
    ],
    required: true,
  },
  
  // The user's written explanation of what happened
  description: String,
  
  // Secure object-storage keys for screenshots of WhatsApp chats, fake receipts, etc.
  evidenceKeys: [String], 

  // ─────────────────────────────────────────────────────────────
  // AI & MACHINE LEARNING SIGNALS (Automated Input)
  // ─────────────────────────────────────────────────────────────
  
  // 0.0 to 1.0 score generated by the fraud detection engine
  aiRiskScore: { type: Number, min: 0, max: 1 },
  
  // Specific flags triggered by the AI (e.g., ["duplicate_image", "abnormal_price"])
  aiSignals: [String], 

  // ─────────────────────────────────────────────────────────────
  // MODERATION WORKFLOW
  // ─────────────────────────────────────────────────────────────
  status: {
    type: String,
    enum: [
      "open",                   // Newly submitted
      "under_review",           // Admin is currently investigating
      "resolved_action_taken",  // Admin banned the user or deleted the property
      "resolved_no_action",     // Investigated, but found no proof of fraud
      "dismissed"               // Spam or false report
    ],
    default: "open",
  },

  // Internal reasoning written by the admin (not visible to users)
  adminNotes: String,
  
  // When the ticket was officially closed
  resolvedAt: Date,

  // ─────────────────────────────────────────────────────────────
  // AUDIT TRAIL
  // ─────────────────────────────────────────────────────────────
  
  // Immutable ledger of every action taken on this report
  history: [{
    status: String,
    changedBy: { type: ObjectId, ref: "Account" },
    changedAt: Date,
    note: String,
  }],

  // Standard timestamps
  createdAt: { type: Date, default: Date.now },
  updatedAt: Date,
};
// Indexes: reportedPropertyId, reportedUserId, reportedBy, status, aiRiskScore