"""Rent estimation module for the HomeLink AI Engine.

Two operating modes are supported:

1. **ML-backed** — when a trained pipeline exists at
   ``ai/models/rent_model.joblib`` it is loaded and used for
   predictions (higher confidence score).

2. **Heuristic baseline** — a deterministic, rule-based fallback that
   guarantees the service works out of the box with no trained model.

Training contract
-----------------
The canonical training script is ``ai/src/train_rent_model.py`` and the
synthetic dataset is generated by ``ai/src/generate_dataset.py``. The
saved pipeline is a scikit-learn ``Pipeline`` whose ``predict`` accepts
a pandas DataFrame with columns, in order::

    ["subcity", "bedrooms", "bathrooms", "area_sqm",
     "has_water_tank", "has_generator", "is_furnished"]

``subcity`` is categorical (one-hot encoded inside the pipeline and
lowercased on both training and serving sides); the remaining columns
are numeric. ``rent_price_etb`` is the prediction target.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional

import pandas as pd

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Paths & feature layout
# ---------------------------------------------------------------------------

AI_DIR = Path(__file__).resolve().parents[1]
MODELS_DIR = AI_DIR / "models"
DATA_DIR = AI_DIR / "data"
RENT_MODEL_PATH = MODELS_DIR / "rent_model.joblib"
DATA_PATH = DATA_DIR / "ethiopia_housing_data.csv"

#: Canonical feature columns a trained model expects (order matters).
MODEL_FEATURE_COLUMNS: List[str] = [
    "subcity",
    "bedrooms",
    "bathrooms",
    "area_sqm",
    "has_water_tank",
    "has_generator",
    "is_furnished",
]

#: Numeric (tree-friendly, passed through) and categorical feature sets.
NUMERIC_FEATURE_COLUMNS: List[str] = [
    "bedrooms",
    "bathrooms",
    "area_sqm",
    "has_water_tank",
    "has_generator",
    "is_furnished",
]
CATEGORICAL_FEATURE_COLUMNS: List[str] = ["subcity"]

#: Target column name used by the training script.
TARGET_COLUMN = "rent_price_etb"

# ---------------------------------------------------------------------------
# Heuristic baseline coefficients (aligned with generate_dataset.py)
# ---------------------------------------------------------------------------

#: Average monthly rent (ETB) per square metre per Addis Ababa subcity.
SUBCITY_BASE_RATE: Dict[str, float] = {
    "bole": 340.0,
    "kirkos": 320.0,
    "arada": 300.0,
    "yeka": 265.0,
    "nifas silk": 240.0,
    "nifas silk-lafto": 240.0,  # alias
    "gulele": 225.0,
    "gullele": 225.0,  # alias
    "kolfe": 215.0,
    "kolfe keranio": 215.0,  # alias
    "lidetta": 210.0,
    "lideta": 210.0,  # alias
    "addis ketema": 205.0,
    "akaky kaliti": 190.0,
}
DEFAULT_SUBCITY_RATE = 250.0

#: Fixed monthly premium (ETB) per additional bedroom / bathroom.
BEDROOM_COEF = 2200.0
BATHROOM_COEF = 1200.0

#: Monthly premium (ETB) for a private water tank / generator.
WATER_TANK_BONUS = 1800.0
GENERATOR_PREMIUM = 2600.0

#: Multiplicative uplift applied to furnished units.
FURNISHED_MULTIPLIER = 1.15

#: Confidence of the heuristic fallback vs. a trained model.
HEURISTIC_CONFIDENCE = 0.58
ML_CONFIDENCE = 0.92


@dataclass(frozen=True)
class RentPrediction:
    """Result of a rent estimation call."""

    estimated_rent_etb: float
    confidence: float
    using_model: bool
    model_name: str
    feature_columns: Optional[List[str]] = field(
        default_factory=lambda: list(MODEL_FEATURE_COLUMNS)
    )


class RentEstimator:
    """Estimates monthly rent in ETB for a residential property."""

    def __init__(self, model_path: Path = RENT_MODEL_PATH) -> None:
        """Initialize the estimator and attempt to load a trained model.

        Args:
            model_path: Path to a ``.joblib`` pipeline, if available.
        """
        self._model_path = model_path
        self._model = None  # type: Optional[object]
        self._load_model()

    # -- public API ---------------------------------------------------------

    def predict(
        self,
        subcity: str,
        bedrooms: int,
        bathrooms: int,
        area_sqm: float,
        has_water_tank: bool,
        has_generator: bool = False,
        is_furnished: bool = False,
    ) -> RentPrediction:
        """Predict the monthly rent in ETB for a property.

        Args:
            subcity: Addis Ababa subcity, e.g. ``"Bole"``.
            bedrooms: Number of bedrooms.
            bathrooms: Number of bathrooms.
            area_sqm: Floor area in square metres.
            has_water_tank: Whether the unit has a private water tank.
            has_generator: Whether the unit has a backup generator.
            is_furnished: Whether the unit is rented furnished.

        Returns:
            A :class:`RentPrediction` with the estimate and confidence.
        """
        if self._model is not None:
            try:
                feature_row = self._build_feature_row(
                    subcity=subcity,
                    bedrooms=bedrooms,
                    bathrooms=bathrooms,
                    area_sqm=area_sqm,
                    has_water_tank=has_water_tank,
                    has_generator=has_generator,
                    is_furnished=is_furnished,
                )
                estimated = float(self._model.predict(feature_row).ravel()[0])
                return RentPrediction(
                    estimated_rent_etb=round(estimated, 2),
                    confidence=ML_CONFIDENCE,
                    using_model=True,
                    model_name=self._model_path.name,
                )
            except Exception as exc:  # noqa: BLE001 - degrade gracefully
                logger.warning("ML rent prediction failed (%s); using heuristic.", exc)

        estimated = self._heuristic_estimate(
            subcity=subcity,
            bedrooms=bedrooms,
            bathrooms=bathrooms,
            area_sqm=area_sqm,
            has_water_tank=has_water_tank,
            has_generator=has_generator,
            is_furnished=is_furnished,
        )
        return RentPrediction(
            estimated_rent_etb=round(estimated, 2),
            confidence=HEURISTIC_CONFIDENCE,
            using_model=False,
            model_name="heuristic-baseline",
        )

    def model_loaded(self) -> bool:
        """Return whether a trained model is currently in use."""
        return self._model is not None

    # -- internals ----------------------------------------------------------

    def _load_model(self) -> None:
        """Attempt to load the trained ``.joblib`` pipeline, if present."""
        try:
            import joblib
        except ImportError:  # pragma: no cover - joblib ships with sklearn
            logger.warning("joblib unavailable; using heuristic baseline.")
            return

        if not self._model_path.exists():
            logger.info("No trained rent model at %s; using heuristic baseline.", self._model_path)
            return

        try:
            self._model = joblib.load(self._model_path)
            logger.info("Loaded rent estimator model from %s", self._model_path)
        except Exception as exc:  # noqa: BLE001
            logger.warning("Failed to load rent model (%s); using heuristic baseline.", exc)
            self._model = None

    def _build_feature_row(
        self,
        subcity: str,
        bedrooms: int,
        bathrooms: int,
        area_sqm: float,
        has_water_tank: bool,
        has_generator: bool,
        is_furnished: bool,
    ) -> pd.DataFrame:
        """Build a single-row DataFrame matching the training feature layout.

        ``subcity`` is lowercased to match the one-hot categories the
        pipeline learned at training time.
        """
        return pd.DataFrame(
            [
                {
                    "subcity": subcity.strip().lower(),
                    "bedrooms": int(bedrooms),
                    "bathrooms": int(bathrooms),
                    "area_sqm": float(area_sqm),
                    "has_water_tank": int(bool(has_water_tank)),
                    "has_generator": int(bool(has_generator)),
                    "is_furnished": int(bool(is_furnished)),
                }
            ],
            columns=MODEL_FEATURE_COLUMNS,
        )

    def _heuristic_estimate(
        self,
        subcity: str,
        bedrooms: int,
        bathrooms: int,
        area_sqm: float,
        has_water_tank: bool,
        has_generator: bool,
        is_furnished: bool,
    ) -> float:
        """Compute a deterministic baseline rent estimate in ETB."""
        rate = SUBCITY_BASE_RATE.get(subcity.strip().lower(), DEFAULT_SUBCITY_RATE)
        estimate = (
            rate * float(area_sqm)
            + int(bedrooms) * BEDROOM_COEF
            + int(bathrooms) * BATHROOM_COEF
        )
        if has_water_tank:
            estimate += WATER_TANK_BONUS
        if has_generator:
            estimate += GENERATOR_PREMIUM
        if is_furnished:
            estimate *= 1.0 + FURNISHED_MULTIPLIER
        return max(estimate, 0.0)
